#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://admin:admin@10.0.25.101:8761/eureka/

spring:
  liquibase:
    enabled: true
    change-log: classpath:config/liquibase/master.xml
    contexts: local
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://internal.mysql.taoqicar.com:3306/tenancy-client?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8

#mybatis:
#  type-aliases-package: